## About This Notebook

In this notebook, we are moving towards a very important new concept called **dictionary**. We already know how to work with lists and lists of lists (which can store data sets). These are however rather basic forms of data. Dictionaries offer us a key/value approach to store data. For example, we might have looped through a list of lists and extracted certain *information* into a dictionary. 
***

## 1. Dictionaries

In the previous mission, we worked with the `AppleStore.csv` data set. The cont_rating column provides a lot of information regarding the content rating of each app. See below:<br>

|Content rating |Number of apps|
|--|--|
|4+|4,433|
|9+|987|
|12+|1,155|
|17+|622|

How can we store the data above? We can do it in two ways:
- Using two separate lists
- Using a single list of lists

In [1]:
# Two lists
content_ratings = ['4+', '9+', '12+', '17+']
numbers = [4433, 987, 1155, 622]

# A list of lists
content_rating_numbers = [['4+', '9+', '12+', '17+'], [4433, 987, 1155, 622]]

Looking at the lists above, you may be confused which content rating corresponds to which number. Each list element has an index number and we will transform the index numbers to content rating values. We can do this using a <b> dictionary </b> like this:

In [2]:
content_ratings = {'4+':4433, '9+':987, '12+':1155, '17+':622}
print(content_ratings)

{'4+': 4433, '9+': 987, '12+': 1155, '17+': 622}


What we have created above are:
- Mapped each content rating to its corresponding number by following an <b>index:value</b> pattern. 
- Seprated each pair with a comma
- Surrounded the sequence with curly braces {}

## 2. Indexing (IMPORTANT)

We can change the index numbers of a list to content rating values in a dictionary. So the mapping between content ratings their corresponding numbers can become much clearer.

Now the question comes, how do we retrieve the individual values of the content_ratings dictionary?  We can use the new indices like we did with the individual list elements following a <b>variable_name[index]</b> pattern like this:


In [4]:
content_ratings = {'4+':4433, '9+':987, '12+':1155, '17+':622}
print(content_ratings['4+'])
print(content_ratings['12+'])

4433
1155


The indexing of dictionary is something different than the list. 
> The order of the dictionary is not necessarily preserved whereas in the lists, the order is **always** preserved.

For example, the index value 0 always retrieves the list element that's positioned first in a list. With dictionaries, there is no direct connection between the index of a value and the position of that value in the dictionary, that means, the order is unimportant. The index value '4+' will retrieve tha value 4433 no matter its position, it could be the first element, or the last element in the dictionary, the retrievd value doesn't matter.

In [1]:
content_ratings = {'4+':4433, '9+':987, '12+':1155, '17+':622}
print(content_ratings)

{'4+': 4433, '9+': 987, '12+': 1155, '17+': 622}


### Task 1.5.2:

1. Retrieve values from the ``content_ratings`` dictionary.
    - Assign the value at index '9+' to a variable named `over_9`.
    - Assign the value at index '17+' to a variable named `over_17`.
2. Print `over_9` and `over_17`.

In [2]:
### Start your code below:
over_9 = content_ratings['9+']
over_17 = content_ratings['17+']
print(over_9)
print(over_17)



987
622


## 3. Alternative way of Creating a Dictionary

There is an alternative way of creating a dictionary like this:
1. Create an empty dictionary.
2. Add values one by one to that empty dictionary.
    - like this: dictionary_name[index] = value
    
Take for example, if we want to add a value 4455 with an index '5+' to a dictionary named content_ratings, we need to use the code:

````python
content_ratings['5+'] = 4455
````

In [7]:
content_ratings = {}
content_ratings['5+'] = 4455

print(content_ratings)

{'5+': 4455}


In [8]:
#To keep adding more values, we can do like this:

content_ratings = {}
content_ratings['4+'] = 4433
content_ratings['9+'] = 987
content_ratings['12'] = 1155
content_ratings['7+'] = 622

print(content_ratings)

{'4+': 4433, '9+': 987, '12': 1155, '7+': 622}


## 4. Key-Value Pairs

A <b>key </b>is a index of a dictionary value. Such as in our example '4+': 4433, the dictionary key is '4+', and the dictionary value is 4433. As a whole, '4+': 4433 is a <b>key-value pair</b>.

All of the data types such as strings, integers, floats, Booleans, lists, and even dictionaries can be dictionary values.

In [10]:
d_1 = { 'key_1' :'value_1',
        'key_2' :1,
        'key_3' :1.832,
        'key_4' :False,
        'key_5' :[1,2,3],
        'key_6' :{'inside key': 100}
}

print(d_1)
print(d_1['key_1'])
print(d_1['key_6'])

{'key_1': 'value_1', 'key_2': 1, 'key_3': 1.832, 'key_4': False, 'key_5': [1, 2, 3], 'key_6': {'inside key': 100}}
value_1
{'inside key': 100}


Different than the dictionary values, dictionary keys can not be [mutable types](https://towardsdatascience.com/https-towardsdatascience-com-python-basics-mutable-vs-immutable-objects-829a0cb1530a) like lists and dictionaries. A TypeError will be thrown if we try to use lists or dictionaries as dictionary keys.

In [11]:
d_1 = { 5 :'int',
        '5' :'string',
        3.5 :'float',
        False :'Boolean'}
print(d_1)

{5: 'int', '5': 'string', 3.5: 'float', False: 'Boolean'}


In [12]:
# A TypeError will be thrown
d_2 = {[1,2,3]:'list'}

TypeError: unhashable type: 'list'

In [13]:
# A TypeError will be thrown
d_2 = {{'key':'value'}:'dictionary'}

TypeError: unhashable type: 'dict'

### Task 1.5.4:

Create the following dictionary and assign it to a variable named ``d_1``:

{'key_1': 'first_value', <br>
 'key_2': 2, <br>
 'key_3': 3.14, <br>
 'key_4': True, <br>
 'key_5': [4,2,1], <br>
 'key_6': {'inner_key' : 6} <br>
 } <br>


In [7]:
### Start your code below:
d_1 = {'key_1': 'first_value', 
'key_2': 2, 
'key_3': 3.14, 
'key_4': True, 
'key_5': [4,2,1], 
'key_6': {'inner_key' : 6} 
} 

print(d_1)

d_2 = {}
d_2['key_1'] = 'first_value'
d_2['key_2'] = 2
d_2['key_3'] = 3.14
d_2['key_4'] = True
d_2['key_5'] = [4,2,1]
d_2['key_6'] = {'inner_key':6}

print(d_2)




{'key_1': 'first_value', 'key_2': 2, 'key_3': 3.14, 'key_4': True, 'key_5': [4, 2, 1], 'key_6': {'inner_key': 6}}
{'key_1': 'first_value', 'key_2': 2, 'key_3': 3.14, 'key_4': True, 'key_5': [4, 2, 1], 'key_6': {'inner_key': 6}}


## 5. Counting with Dictionaries

The code below will show you how to update or change the dictionary values within an existing dictionary.

In [15]:
content_ratings = {'4+':4433, '9+':987, '12+':1155, '17+':622}

# Change the value corresponding to the dictionary key '4+' from 4433 to 1.
content_ratings['4+'] = 1

# Add 13 to the value corresponding to the dictionary key '9+'.
content_ratings['9+'] +=13

# Subtract 1128 from the value corresponding to the dictionary key '12+'.
content_ratings['12+'] -= 1128

# Change the value corresponding to the dictionary key '17+' from 622 (integer) to '511' (string).
content_ratings['17+'] = '511'

print(content_ratings)

{'4+': 1, '9+': 1000, '12+': 27, '17+': '511'}


**Now we can combine the updating dictionary values technique with what we already know to count how many times each unique content rating occurs in our data set.** Let's start with this list: ['4+', '4+', '4+', '9+', '9+', '12+', '17+'], which stores a few content ratings. To count how many times each rating occurs in this short list, we should:
- Create a dictionary where all the values (initial count) are all 0:{'4+': 0, '9+': 0, '12+': 0, '17+': 0}.
- Loop through the list ['4+', '4+', '4+', '9+', '9+', '12+', '17+'], and for each iteration:
    - Check whether the iteration variable exists as a key in the previously created dictionary.
    - If it exists, then increment the dictionary value at that key by 1.

In [8]:
content_ratings = {'4+':0, '9+':0, '12+':0, '17+':0}
ratings = ['4+','4+','4+','9+','9+','12+','17+']

for c_rating in ratings:
    if c_rating in content_ratings:
        content_ratings[c_rating] += 1
content_ratings

{'4+': 3, '9+': 2, '12+': 1, '17+': 1}

To get a better overview, we can print the content_rating dictionary inside the for loop and see the changes that it makes every time:

In [17]:
content_ratings = {'4+':0, '9+':0, '12+':0, '17+':0}
ratings = ['4+','4+','4+','9+','9+','12+','17+']

for c_rating in ratings:
    if c_rating in content_ratings:
        content_ratings[c_rating] += 1
    print(content_ratings)
print('Final dictionary:')
content_ratings

{'4+': 1, '9+': 0, '12+': 0, '17+': 0}
{'4+': 2, '9+': 0, '12+': 0, '17+': 0}
{'4+': 3, '9+': 0, '12+': 0, '17+': 0}
{'4+': 3, '9+': 1, '12+': 0, '17+': 0}
{'4+': 3, '9+': 2, '12+': 0, '17+': 0}
{'4+': 3, '9+': 2, '12+': 1, '17+': 0}
{'4+': 3, '9+': 2, '12+': 1, '17+': 1}
Final dictionary:


{'4+': 3, '9+': 2, '12+': 1, '17+': 1}

How it's time to read in our data set (AppleStore.csv) and use the technique we learned above to count number of times each unique content rating occurs.

### Task 1.5.5:
Count the number of times each unique content rating occurs in the data set.
1. Create a dictionary named `content_ratings` where the keys are the unique content ratings and the values are all 0 (the values of 0 are temporary at this point, and they'll be updated). This dictionary should look like a set with pairing key (Feel free to take a look at the example above).
2. Loop through the apps_data list of lists. Make sure you don't include the header row. For each iteration of the loop:
    - Assign the content rating value to a variable named `c_rating`. The content rating is at index number 10 in each row.
    - Check whether ``c_rating`` exists as a key in ``content_ratings``. If it exists, then increment the dictionary value at that key by 1 (the key is equivalent to the value stored in c_rating).
3. Outside the loop, print `content_ratings` to check whether the counting worked as expected.

In [12]:
opened_file = open('AppleStore.csv', encoding='utf8')
from csv import reader
read_file = reader(opened_file)
apps_data = list(read_file)
### Start your code below:
content_ratings = {'4+':0, '9+':0, '12+':0, '17+':0}

for row in apps_data[1:]:
    c_rating = row[10]
    
    if c_rating in content_ratings:
        content_ratings[c_rating] += 1
        
print(content_ratings)
        
    



{'4+': 4433, '9+': 987, '12+': 1155, '17+': 622}


## 6. Finding the Unique Values

In the example that we worked in the previous session, we knew each of the unique values we want to count beforehand. We if we didn't know what the unique content ratings are. For example, what should we do if we don't have enough information to create the dictionary {'4+': 0, '9+': 0, '12+': 0, '17+': 0}.

We can update code that we did for the list ['4+', '4+', '4+', '9+', '9+', '12+', '17+'] to accomodate this charateristic. 
In in addition to the <b>if </b>statement, we also added an <b>else </b>statement. If this dictionary key does not exist in our dictionary, then we create a new key-value pair in the content_ratings dictionary, where the dictionary key is the iteration variable (c_rating) and the dictionary value is 1.


In [19]:
content_ratings = {}
ratings = ['4+','4+','4+','9+','9+','12+','17+']

for c_rating in ratings:
    if c_rating in content_ratings:
        content_ratings[c_rating] += 1
    else:
        content_ratings[c_rating] = 1
content_ratings

{'4+': 3, '9+': 2, '12+': 1, '17+': 1}

To get a better overview, we can print the content_rating dictionary inside the for loop and see the changes that it makes every time:

In [20]:
content_ratings = {}
ratings = ['4+','4+','4+','9+','9+','12+','17+']

for c_rating in ratings:
    if c_rating in content_ratings:
        content_ratings[c_rating] += 1
    else:
        content_ratings[c_rating] = 1
    print(content_ratings)
    
print('Final dictionary:')
content_ratings

{'4+': 1}
{'4+': 2}
{'4+': 3}
{'4+': 3, '9+': 1}
{'4+': 3, '9+': 2}
{'4+': 3, '9+': 2, '12+': 1}
{'4+': 3, '9+': 2, '12+': 1, '17+': 1}
Final dictionary:


{'4+': 3, '9+': 2, '12+': 1, '17+': 1}

### Task 1.5.6:
Now let's apply what we have just learned in our data set:

Count the number of times each unique content rating occurs in the data set while finding the unique values automatically.
1. Create an empty dictionary named `content_ratings`.
2. Loop through the `apps_data` list of lists (make sure you don't include the header row). For each iteration of the loop:
    - Assign the content rating value to a variable named `c_rating`. The content rating is at index number 10.
    - Check whether c_rating exists as a key in `content_ratings`.
        - If it exists, then increment the dictionary value at that key by 1 (the key is equivalent to the value stored in c_rating).
        - Else, create a new key-value pair in the dictionary, where the dictionary key is c_rating and the dictionary value is 3. Outside the loop, print content_ratings to check whether the counting worked as expected.

In [15]:
opened_file = open('AppleStore.csv', encoding='utf8')
from csv import reader
read_file = reader(opened_file)
apps_data = list(read_file)

### Start your code here:
content_ratings = {}

for row in apps_data[1:]:
    c_rating = row[10]
    if c_rating in content_ratings:
        content_ratings[c_rating] += 1
    else:
        content_ratings[c_rating] = 1
    
print(content_ratings)



{'4+': 4433, '12+': 1155, '9+': 987, '17+': 622}


In [43]:
opened_file = open('PersonsN4J.csv', encoding='utf8')
from csv import reader
read_file = reader(opened_file, delimiter = ";")
person_data = list(read_file)

### Start your code here:
person_nr = {}

for row in person_data[1:]:
    no_mention = row[3]
    if no_mention in person_nr:
        person_nr[no_mention] += 1
    else:
        person_nr[no_mention] = 1
    
# if  person_nr > 1:
for each in person_nr:
    if person_nr[each] > 1:
        print(each, "=", person_nr[each])



pe__stephan_frauendorfer_StB_I_7 = 3
pe__jakob_chetner_StB_I_7 = 5
pe__konrad_chetner_StB_I_7 = 3
pe__johann_hannsgraf_StB_I_40 = 2
pe__hermann_von_eslarn_StB_I_54 = 2
pe__stephan_leyttner_StB_I_54 = 4
pe__michael_affer_StB_I_72 = 4
pe__niklas_kamrer_StB_I_77 = 2
pe__katharina_chettnerin_StB_I_78 = 2
pe__niklas_chamrer_StB_I_77 = 2
pe__heinrich_kamrer_StB_I_80 = 2
pe__katharina_von_steyr_StB_I_99 = 2
pe__heinrich_von_steyr_StB_I_99 = 2
pe__meinhard_vischer_StB_I_134 = 2
pe__jakob_gunser_StB_I_136 = 3
pe__berthold_gevater_StB_I_136 = 2
pe__ulrich_rude_StB_I_136 = 2
pe__niklas_des_hosen_sun_StB_I_136 = 2
pe__niklas_hosen_StB_I_136 = 3
pe__brigitta_hosin_StB_I_136 = 2
pe__margarethe_von_den_schotten_StB_I_143 = 2
pe__ulrich_von_den_schotten_StB_I_143 = 2
pe__christian_platner_StB_I_179 = 2
pe__anna_gusterin_StB_I_199 = 2
pe__niklas_guster_StB_I_199 = 2
pe__kunigunde_vischerin_StB_I_240 = 2
pe__paul_vischer_StB_I_240 = 2
pe__heinrich_schepach_StB_I_243 = 5
pe__otto_hakcher_StB_I_267 = 3
pe

## 7. Proportions and Percentages

The following table is known as the frequency table. A frequency is the number of times a unique value occurs.

|Content rating|Number of apps (frequency)|
|--|--|
|4+|4,433|
|9+|987|
|12+|1,155|
|17+|622|

4+ occurs 4,433 times, so it has a frequency of 4,433. 12+ has a frequency of 1,155. 9+ has a frequency of 987. 17+ has the lowest frequency: 622.

When we analyze the data set, it might also be interesting to look at the following questions:
- What proportion of apps have a content rating of 4+?
- What percentage of apps have a content rating of 17+?
- What percentage of apps can a 15-year-old download?

To get the proportion of apps with a content rating of 4+, we can use the number of 4+ apps divide by the total number of apps like this:
4,443/7,197

Instead of fraction, we can also express proportion as a decimal between 0 and 1. So the result of 4,443/7,197 will be 0.62.

The percentage of 4+ apps we can get it by simply multiplying the proportions by 100, so it will be 62%.

## 8. Looping over Dictionaries

We can transform the frequencies to proportions or percentages individually by performing the required arithmetical operations like this:

In [23]:
content_ratings = {'4+':4433, '9+':987, '12+':1155, '17+':622}
total_number_of_apps = 7197

content_ratings['4+']/=total_number_of_apps
content_ratings['9+']/=total_number_of_apps
content_ratings['12+']/=total_number_of_apps
content_ratings['17+']/=total_number_of_apps

print(content_ratings)

{'4+': 0.6159510907322495, '9+': 0.13714047519799916, '12+': 0.16048353480616923, '17+': 0.08642489926358204}


It can be very cumbersome to update each and every content_rating dictionary value manually. Therefore, we can use a for loop to iterate over a dictionary.

In [24]:
content_ratings = {'4+':4433, '9+':987, '12+':1155, '17+':622}

for iteration_variable in content_ratings:
    print(iteration_variable)

4+
9+
12+
17+


We can also use the dictionary keys to access the dictionary values within the loop:

In [25]:
content_ratings = {'4+':4433, '9+':987, '12+':1155, '17+':622}

for iteration_variable in content_ratings:
    print(iteration_variable)
    print(content_ratings[iteration_variable])

4+
4433
9+
987
12+
1155
17+
622


With the technique above, we can update the dictionary values within loop:

In [26]:
content_ratings = {'4+':4433, '9+':987, '12+':1155, '17+':622}
total_number_of_apps = 7197

for iteration_variable in content_ratings:
    content_ratings[iteration_variable] /= total_number_of_apps
print(content_ratings)

{'4+': 0.6159510907322495, '9+': 0.13714047519799916, '12+': 0.16048353480616923, '17+': 0.08642489926358204}


## 9. Small Bonus (OPTIONAL)
The looping through dictionaries which we used in this notebook is really used only for training purposes. In a productive and professional code, you would not want to use it. 

Here is a recommendation by our RBCZ colleague *Jakub Korecek*:
>  Dictionary has one important and very useful method to check whether a key is ``existent``. This method is called ``get()``.
The useful part is, we can assign value if a key does not exist instead of having KeyError. The default values is ``None``, but we can set it up.

In [2]:
test_dict = {'A':1,'B':2}
print(test_dict.get('A'))
print(test_dict.get('C'))
print(test_dict.get('C','KEY DO NOT EXISTS'))

1
None
KEY DO NOT EXISTS


> There is another way to iterate over Dictionary. This way is better from performance point of view. It is done by method called ``items()``.

In [3]:
test_dict = {'A':1,'B':2}
for key,value in test_dict.items():
    print(key,value)

A 1
B 2
